### PR TITLE
Merge master into gh-pages

### PR DESCRIPTION
**Pull request by MagicMarvMan**
Hello.

We need to merge master into gh-pages to populate the last changes, I think.

So it would be cool, if you could do this.

Thank you!

### CODE REVIEW

**Comment by niccokunzmann** [comment]
@MagicMarvMan There are merge conflicts. Which version should we use?

**Comment by MagicMarvMan** [comment]
@niccokunzmann Fixed :)

**Comment by MagicMarvMan** [comment]
Shit!!! I accidently merged it!!! Can you undo it, please?

**Comment by MagicMarvMan** [comment]
@niccokunzmann 
**Bump:** What do you think about this PR?

**Comment by niccokunzmann** [comment]
@MagicMarvMan I think, I first want to know if it builds...

**Pull request merged**
